### ISSUE TITLE
How to cite the book?

### ISSUE THREAD

**Issue by HeidiSeibold** [mlr-org/mlr3book#167]
If I wanted to cite the book, how would I do it?

### TODOs:

- [ ] Figure out how to best cite the book
- [ ] Add the info to the book
- [ ] Optional: add the info in a CITATION file in the repo

### Helpful ressource:

This is how the Turing Way does it: https://the-turing-way.netlify.com/introduction/introduction#Citing-The-Turing-Way

**Comment by berndbischl** [comment]
1) thanks!

2) 
> If I wanted to cite the book, how would I do it?
where do you currently want to cite it? out of curiosity

3) I guess the "turning way" also has release cycles and versions correct? if we had that, putting the pdf somewhere citable would not be problem. e.g. we put the mlr2 tutorial on arxiv

@pat-s  @mllg

**Comment by HeidiSeibold** [comment]
> where do you currently want to cite it? out of curiosity

I don't. I just noticed that the book doesn't have the info and I'm just really nice ;)

> I guess the "turing way" also has release cycles and versions correct?

They put certain versions on zenodo yes. I don't know how exactly it is organized.
