### ISSUE TITLE
Add Preamble

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3book#432]
Suggested content to include

* [x] Quickstart
* [ ] ~Description of sugar and why we use it instead of R6 - #408~ #437 
* [x] How to use the book (e.g., if interested in technical details, or exercises, or extension, or special tasks...)
* [x] Discussion about included exercises and symbols that indicate difficult (e.g., 🚩)  and optional sections (e.g., ⭐).
* [ ] ~Basic history: what does mlr3 stand for, why upgrade from mlr~ #437 
* [ ] ~Very short comparison to caret and tidymodels (target audience: new people to ML in R and/or people who want more flexibility over ML code)~  #437 
* [x] Installation guidelines. Links to GitHub (mlr3 and others) - https://github.com/mlr-org/mlr3book/issues/390
* [x] Links to mattermost here and including a call to action for contibutors, developers, etc. Also a good place to add links to the website and, if you start doing more GSOC/Outreachy, then a direct link to internship page.
* [x] Make clear where issues should be opened and how to contribute.
* [x] Citation info
* [x] mlr3 styleguide
